services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/users.yml:/data/users.yml
    environment:
      - DOZZLE_REMOTE_AGENT=192.168.100.102:7007|docker-01
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_AUTH_TTL=48h
